name: Release

on:
  workflow_dispatch:
    inputs:
      next:
        description: "Version or major (maj), minor (min, feature, feat) or patch (bug, bugfix)"
        required: true

env:
  GITHUB_API_TOKEN: ${{ secrets.GH_API_TOKEN }}

jobs:
  release:
    name: Release "${{ github.event.inputs.next }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v3

      - name: Release
        run: bin/changelog release ${{ github.event.inputs.next }} --target=${GITHUB_REF##*/} --push --no-interaction


